export const alumniData = [
    {
      id: "cse1",
      src: require("./images/Manoj.jpg"),
      name: "Manoj",
      phone: "6384554049",
      location: "Salem",
      year: "2021",
      company: "FaceBook",
      email: "manoj123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
      contest: "LeetCode, CodingNinjas,HackerEarth",
    },
    {
      id: "cse2",
      src: require("./images/Shridhar.jpg"),
      name: "Shridhar",
      phone: "6384554049",
      location: "Chennai",
      year: "2021",
      company: "Amazon",
      email: "shridhar123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
       "Experienced Senior Software Engineer with a demonstrated history of working in the computer software industry. Skilled in SQL Database, DOTNET , MVC , AngularJS. Oracle | Netsuite SuiteFoundation Certified Recipient of Star Award,Spot Award,Team Award Won 2,00,000 price in SmartIndiaHackathon",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "cse3",
      src: require("./images/Selva.png"),
      name: "Selva",
      phone: "6384554049",
      location: "Banglore",
      year: "2021",
      company: "Google",
      email: "selva123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth,CodingNinjas",
      achievements:
      " Ruby on Rails | REST APIs | AWS | Full Stack Developer, Good knowledge of software development life cycle that includes requirement analysis, development, testing, implementation of Ruby on rails applications, Good experience in implementing design changes, functionality implementation, resolving performance issues, continuous integration and optimizing the code, Have designed and implementation of web services(API Implementation)",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "cse4",
      src: require("./images/Rajesh.jpg"),
      name: "Rajesh",
      phone: "7639608205",
      location: "Hyderabad",
      year: "2021",
      company: "Microsoft",
      email: "rajesh123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "A Backend developer, first to be certified by Microsoft as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Microsoft, Full Sponsorship by Microsoft for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks,A good Business Planner certified by Microsoft",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "cse5",
      src: require("./images/Divya.jpg"),
      name: "Divya",
      phone: "8838883776",
      location: "Mumbai",
      year: "2021",
      company: "Reliance",
      email: "divya123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "Divya from team Tradent who participated in Smart India Hackathon 2020 conducted by MHRD Govt of India. It is a National level innovation hackathon conducted by central government along with various ministries where in which more than 3 lakh Students from various top educational institutes across the nation have participated and come up with an innovative solution for the Problem statement listed by the respective Ministry.",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "cse6",
      src: require("./images/saru.jpg"),
      name: "Saru",
      phone: "6381854049",
      location: "Mumbai",
      year: "2021",
      company: "NetFlix",
      email: "saru123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "aids1",
      src: require("./images/Abinaya.jpg"),
      name: "Abinaya",
      phone: "6384554049",
      location: "chennai",
      year: "2021",
      company: "Zoho",
      email: "abinaya123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "Research and Developer by Machine Learning,Good Developer certified by Zoho,Have good network in database,Skilled Trainer",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "aids2",
      src: require("./images/mithuna.jpg"),
      name: "Mithuna",
      phone: "6384554049",
      location: "Hyderabad",
      year: "2021",
      company: "Google",
      email: "mithu123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "A Skilled developer, first to be certified by Google as Associate Android Developer in the world, Lead Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Google, Full Sponsorship by Google for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "aids3",
      src: require("./images/sharmi.jpg"),
      name: "Sharmila",
      phone: "6384554049",
      location: "Microsoft",
      year: "2021",
      company: "Banglore",
      email: "sharmi123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "Senior Android Engineer at Backbase,Demonstrated the ability to handle both design and development in an efficient way,Mentor at Mindorks",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "aids4",
      src: require("./images/Priya.jpg"),
      name: "Priya",
      phone: "6384554049",
      location: "Banglore",
      year: "2021",
      company: "Apple",
      email: "priya123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        " He has won 2 bronze medals and  one silver medal in Hackathon  in the held at NationalLevelHackathon in May 2022.Apple visited our campus on 9th June 2022 and I was felicitated by our honorable Co-Chairman, Chief Director, Director, Dean ET and VP Academics.Good Role in DataScientist,Won many Rewards through DataScientist",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "it1",
      src: require("./images/Kavipriya.jpg"),
      name: "Kavipriya",
      phone: "6384784049",
      location: "Hyderabad",
      year: "2021",
      company: "Google",
      email: "kavipriya123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "A Unicorn developer, first to be certified by Google as Associate Backend Developer in the world, Droidcon Speaker",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "it2",
      src: require("./images/Krishna.jpg"),
      name: "Krishna",
      phone: "6386381855",
      location: "Delhi",
      year: "2021",
      company: "Microsoft",
      email: "krishna123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "Ruby on Rails | REST APIs | AWS | Full Stack Developer, Good knowledge of software development life cycle that includes requirement analysis, development, testing, implementation of Ruby on rails applications, Good experience in implementing design changes, functionality implementation, resolving performance issues, continuous integration and optimizing the code, Have designed and implementation of web services(API Implementation)",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "it3",
      src: require("./images/Nirmala.jpg"),
      name: "Nirmala",
      phone: "6376396082",
      location: "Chennai",
      year: "2021",
      company: "Zoho",
      email: "nirmala123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "A Fullstack web developer, first to be certified by Zoho as Associate Frontend Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "it4",
      src: require("./images/Naveen.jpg"),
      name: "Naveen",
      phone: "6356349741",
      location: "Hyderabad",
      year: "2021",
      company: "Amazon",
      email: "naveen123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "A Product developer, first to be certified by Amozon as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "it5",
      src: require("./images/Monisha.jpg"),
      name: "Monisha",
      phone: "6384678324",
      location: "Banglore",
      year: "2021",
      company: "Wipro",
      email: "moni123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "Ruby on Rails | REST APIs | AWS | Full Stack Developer, Good knowledge of software development life cycle that includes requirement analysis, development, testing, implementation of Ruby on rails applications, Good experience in implementing design changes, functionality implementation, resolving performance issues, continuous integration and optimizing the code, Have designed and implementation of web services(API Implementation)",
      contest: "LeetCode, CodingNinjas",
    },
    {
      id: "it6",
      src: require("./images/Abinath.jpg"),
      name: "Abinath",
      phone: "6384890345",
      location: "Salem",
      year: "2021",
      company: "Virtusa",
      email: "abinath123@gmail.com",
      skills: "C++,JAVA,PYTHON,C",
      eventsParticipated: "Smart india hackathon",
      platforms: "Leetcode,HackerRank,HackerEarth",
      achievements:
        "A product developer, first to be certified by Virtusa as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, Full Sponsorship by Virtusa for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks,Creative thinker certified by Virtusa",
      contest: "LeetCode, CodingNinjas",
    },
  ];